import React, { useState, useRef, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { DEFAULT_BRAND, createPoster, exportCarousel, downloadBlob, wrapPosterText } from './creatorTools';
import { getAnimationPresetsForElement } from '../../canvas/animationRegistry';
import './CreatorStudio.css';

function AudioWaveform({source}) {
    const canvas=useRef(null),audio=useRef(null);const [error,setError]=useState('');
    useEffect(()=>{if(!source)return;let active=true;const context=new (window.AudioContext||window.webkitAudioContext)();setError('');
        (async()=>{const response=await fetch(source);const buffer=await context.decodeAudioData(await response.arrayBuffer());if(!active)return;const target=canvas.current,ctx=target.getContext('2d'),data=buffer.getChannelData(0);ctx.clearRect(0,0,800,90);ctx.fillStyle='#0284c7';for(let x=0;x<800;x++){const start=Math.floor(x*data.length/800),end=Math.max(start+1,Math.floor((x+1)*data.length/800));let peak=0;for(let j=start;j<end;j++)peak=Math.max(peak,Math.abs(data[j]||0));ctx.fillRect(x,45-peak*42,1,Math.max(1,peak*84));}})().catch(e=>{if(active)setError(e.message);}).finally(()=>context.close());return()=>{active=false;};},[source]);
    if(!source)return <p>Attach audio to this frame to inspect its waveform.</p>;
    return <div><canvas ref={canvas} width="800" height="90" aria-label="Audio waveform; click to seek" onClick={e=>{const a=audio.current;if(a&&Number.isFinite(a.duration)){const b=e.currentTarget.getBoundingClientRect();a.currentTime=(e.clientX-b.left)/b.width*a.duration;}}}/><audio ref={audio} controls src={source}/>{error&&<p role="alert">{error}</p>}</div>;
}
export default function CreatorStudio({elements,selectedIds=[],frames,currentFrameIndex,canvasSize,canvasProps,onElements,onDocument,onSelect,onAudio,onFrameDuration}) {
    const [open,setOpen]=useState(false),[tab,setTab]=useState('Poster'),[brand,setBrand]=useState(()=>{try{return {...DEFAULT_BRAND,...JSON.parse(localStorage.getItem('sketchydraw.creatorBrand')||'{}')};}catch{return DEFAULT_BRAND;}});
    const [title,setTitle]=useState(''),[body,setBody]=useState(''),[cta,setCta]=useState(''),[preset,setPreset]=useState('portrait'),[template,setTemplate]=useState('lesson'),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[caption,setCaption]=useState(''),[start,setStart]=useState(0),[end,setEnd]=useState(3000);
    const frame=frames[currentFrameIndex]||{};
    useEffect(()=>{if(!open)return;const close=e=>{if(e.key==='Escape')setOpen(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[open]);
    const patch=(id,change)=>onElements(elements.map(e=>e.id===id?{...e,...change}:e));
    const task=async action=>{setBusy(true);setStatus('Working…');try{await action();}catch(e){setStatus(e.message);}finally{setBusy(false);}};
    const fileData=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});
    return <><button className="creator-launch" type="button" onClick={()=>setOpen(true)}>2D Studio</button>{open&&createPortal(<div className="creator-backdrop"><section className="creator-panel" role="dialog" aria-modal="true" aria-label="2D Creator Studio">
        <header><h2>2D Creator Studio</h2><button type="button" autoFocus onClick={()=>setOpen(false)}>Close</button></header>
        <nav>{['Poster','Brand kit','Timeline','Layers','Audio & captions'].map(t=><button type="button" key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
        {tab==='Poster'&&<div className="creator-fields"><label>Format<select value={preset} onChange={e=>setPreset(e.target.value)}><option value="portrait">Portrait 1080×1350</option><option value="post">Square 1080×1080</option><option value="story">Story 1080×1920</option></select></label><label>Template<select value={template} onChange={e=>setTemplate(e.target.value)}><option value="lesson">Educational lesson</option><option value="quote">Quote</option><option value="promo">Promotion</option></select></label><label>Headline<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Body (one item per line)<textarea rows="4" value={body} onChange={e=>setBody(e.target.value)}/></label><label>Call to action<input value={cta} onChange={e=>setCta(e.target.value)}/></label><p>Creating a poster replaces the current board. Export your JSON first if needed.</p><button disabled={busy} onClick={()=>task(async()=>{const doc=createPoster({preset,template,title,body,cta,brand});onDocument(doc);setStatus('Poster created. Edit objects on the canvas or export the carousel PNG ZIP.');})}>Create poster / replace board</button><button disabled={busy} onClick={()=>task(async()=>{const active=frames.map((f,i)=>i===currentFrameIndex?{...f,elements}:f);const blob=await exportCarousel(active,canvasProps,canvasSize,preset,(n,total)=>setStatus(`Exporting slide ${n}/${total}`));downloadBlob(blob,'sketchydraw-carousel.zip');setStatus('Carousel ZIP downloaded.');})}>Export all frames as PNG ZIP</button></div>}
        {tab==='Brand kit'&&<div className="creator-fields">{[['name','Brand name'],['font','Font family'],['accent','Accent'],['background','Background'],['foreground','Text color']].map(([key,label])=><label key={key}>{label}<input type={['accent','background','foreground'].includes(key)?'color':'text'} value={brand[key]} onChange={e=>setBrand({...brand,[key]:e.target.value})}/></label>)}<label>Logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files[0];if(f)task(async()=>{if(f.size>2*1024*1024)throw new Error('Use a logo under 2 MB.');setBrand({...brand,logo:await fileData(f)});setStatus('Logo loaded.');});}}/></label>{brand.logo&&<><img src={brand.logo} width="80" alt="Brand logo"/><button onClick={()=>setBrand({...brand,logo:''})}>Remove logo</button></>}<button onClick={()=>task(async()=>{localStorage.setItem('sketchydraw.creatorBrand',JSON.stringify(brand));setStatus('Brand kit saved on this browser.');})}>Save brand kit</button><p>Brand settings apply to newly created posters.</p></div>}
        {tab==='Timeline'&&<div><label>Frame duration (ms)<input type="number" min="1000" step="100" value={frame.durationMs||4000} onChange={e=>onFrameDuration(Math.max(1000,Number(e.target.value)||1000))}/></label><button onClick={()=>{onElements(elements.map((e,i)=>({...e,animation:{...e.animation,type:'fadeIn',durationMs:500,delayMs:i*600,dependsOnId:null,dependencyMode:'absolute',beforeStart:'hidden',afterEnd:'visible',loop:false}})));onFrameDuration(Math.max(4000,elements.length*600+500));setStatus('Sequential reveal applied.');}}>Reveal objects in order</button><p>Edit each object’s effect, start time and duration. Play frames to preview.</p>{elements.map(e=><div className="creator-timing" key={e.id}><span>{e.text?.slice(0,25)||e.type}</span><div className="creator-time-track" title={`Starts at ${e.animation?.delayMs||0} ms`}><div style={{marginLeft:`${Math.min(95,100*(e.animation?.delayMs||0)/(frame.durationMs||4000))}%`,width:`${Math.max(2,Math.min(100,100*(e.animation?.durationMs||1000)/(frame.durationMs||4000)))}%`}}/></div><select aria-label="Animation effect" value={e.animation?.type||'none'} onChange={v=>patch(e.id,{animation:{...e.animation,type:v.target.value,beforeStart:'hidden',afterEnd:'visible'}})}>{getAnimationPresetsForElement(e).map(p=><option key={p.type} value={p.type}>{p.label}</option>)}</select><label>Start ms<input type="number" min="0" value={e.animation?.delayMs||0} onChange={v=>patch(e.id,{animation:{...e.animation,delayMs:Math.max(0,Number(v.target.value)||0),dependsOnId:null}})}/></label><label>Duration ms<input type="number" min="1" value={e.animation?.durationMs||1000} onChange={v=>patch(e.id,{animation:{...e.animation,durationMs:Math.max(1,Number(v.target.value)||1)}})}/></label><label>Loop<input type="checkbox" checked={!!e.animation?.loop} onChange={v=>patch(e.id,{animation:{...e.animation,loop:v.target.checked}})}/></label></div>)}</div>}
        {tab==='Layers'&&<div><button disabled={selectedIds.length<2} onClick={()=>{const chosen=elements.filter(e=>selectedIds.includes(e.id)&&!e.creatorLocked);if(chosen.length<2){setStatus('Select at least two unlocked objects.');return;}const id=`group-${Date.now()}`,x=Math.min(...chosen.map(e=>e.x))-16,y=Math.min(...chosen.map(e=>e.y))-16,right=Math.max(...chosen.map(e=>e.x+(e.w||0)))+16,bottom=Math.max(...chosen.map(e=>e.y+(e.h||0)))+16;onElements([{id,type:'rect',x,y,w:right-x,h:bottom-y,fill:'transparent',stroke:brand.accent,strokeWidth:1,opacity:1},...elements.map(e=>chosen.includes(e)?{...e,parentId:id}:e)]);onSelect([id]);setStatus('Objects grouped inside a parent rectangle.');}}>Group selected objects</button><button onClick={()=>{const ids=new Set(selectedIds);onElements(elements.map(e=>ids.has(e.parentId)?{...e,parentId:null}:e));setStatus('Selected parent’s children ungrouped.');}}>Ungroup selected parent</button><p>Top rows are in front. Locked objects resist canvas moves and deletion; unlock here to edit.</p>{elements.slice().reverse().map(e=><div className="creator-layer" key={e.id}><button onClick={()=>{onSelect([e.id]);setOpen(false);}}>{e.text?.slice(0,35)||e.type}</button><button onClick={()=>patch(e.id,{creatorLocked:!e.creatorLocked})}>{e.creatorLocked?'Unlock':'Lock'}</button><button disabled={e.creatorLocked} onClick={()=>{const i=elements.indexOf(e),next=[...elements];if(i<next.length-1){[next[i],next[i+1]]=[next[i+1],next[i]];onElements(next);}}}>Forward</button><button disabled={e.creatorLocked} onClick={()=>{const i=elements.indexOf(e),next=[...elements];if(i>0){[next[i],next[i-1]]=[next[i-1],next[i]];onElements(next);}}}>Back</button><button disabled={e.creatorLocked} onClick={()=>onElements(elements.filter(item=>item.id!==e.id))}>Delete</button></div>)}</div>}
        {tab==='Audio & captions'&&<div className="creator-fields"><label>Attach frame audio<input type="file" accept="audio/*" onChange={e=>{const f=e.target.files[0];if(f)task(async()=>{if(f.size>25*1024*1024)throw new Error('Use audio under 25 MB.');onAudio(await fileData(f),{name:f.name,mimeType:f.type});setStatus('Audio attached to this frame.');});}}/></label><AudioWaveform source={frame.audioDataUrl}/><label>Caption<textarea value={caption} onChange={e=>setCaption(e.target.value)}/></label><label>Start ms<input type="number" min="0" value={start} onChange={e=>setStart(Number(e.target.value))}/></label><label>End ms<input type="number" min="1" value={end} onChange={e=>setEnd(Number(e.target.value))}/></label><button onClick={()=>task(async()=>{if(!caption.trim()||start<0||end<=start)throw new Error('Enter caption text and a valid time range.');const wrapped=wrapPosterText(caption,canvasSize.width-120,30,brand.font);if(wrapped.h>canvasSize.height/3)throw new Error('Caption is too long.');onElements([...elements,{id:`caption-${Date.now()}`,type:'text',x:60,y:canvasSize.height-wrapped.h-60,w:canvasSize.width-120,h:wrapped.h,text:wrapped.text,fontSize:30,lineHeight:wrapped.lineHeight,fontFamily:brand.font,stroke:brand.foreground,fill:'transparent',bold:true,opacity:1,animation:{type:'appear',delayMs:start,durationMs:end-start,beforeStart:'hidden',afterEnd:'hidden',loop:false}}]);onFrameDuration(Math.max(frame.durationMs||4000,end));setCaption('');setStatus('Timed caption added as an editable text object.');})}>Add timed caption</button><p>Waveform click seeks audio. Caption timings use this frame’s timeline.</p></div>}
        <footer role="status">{status}</footer>
    </section></div>,document.body)}</>;
}
