export const PLAN_CODES = Object.freeze({
    INR_MONTHLY: "SKETCHY_MONTHLY_349",
    INR_SIX_MONTHS: "SKETCHY_6_MONTHS_1494",
    INR_ANNUAL: "SKETCHY_ANNUAL_1999",

    USD_MONTHLY: "SKETCHY_MONTHLY_USD_9",
    USD_SIX_MONTHS: "SKETCHY_6_MONTHS_USD_40",
    USD_ANNUAL: "SKETCHY_ANNUAL_USD_75",
});
