location = /robots.txt {
    root /var/www/sketchydraw-ui;
    try_files $uri =404;
    access_log off;
}
location = /sitemap.xml {
    root /var/www/sketchydraw-ui;
    try_files $uri =404;
    access_log off;
}
location / {
    root /var/www/sketchydraw-ui;
    try_files $uri $uri/ /index.html;
}
